name: VPS

on:
  workflow_dispatch:

jobs:
  secure-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl

      - name: Set Root Password
        run: |
          # Set root password to 'root'
          echo "root:root" | sudo chpasswd
          
          # Enable root login via SSH (if disabled)
          sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          
          # Restart SSH service using the correct command
          sudo systemctl restart ssh

      - name: Install Tailscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/tailscale_1.82.0_amd64.deb -o tailscale.deb
          sudo dpkg -i tailscale.deb
          rm tailscale.deb

      - name: Generate Random VPS Name
        run: |
          # Generate random VPS name using GitHub run ID
          VPS_NAME="gh-vps-${{ github.run_id }}"
          echo "VPS_NAME=$VPS_NAME" >> $GITHUB_ENV

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and the random VPS name
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=$VPS_NAME
          
          # Wait for Tailscale to assign an IP
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Verify SSH Accessibility
        run: |
          # Test SSH connection to the VPS via Tailscale IP
          echo "Testing SSH connection to $TAILSCALE_IP"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$TAILSCALE_IP "echo 'SSH connection successful!'"
          
      - name: Maintain Connection
        run: |
          echo "VPS IP: $TAILSCALE_IP"
          echo "Username: root"
          echo "Password: root"
          
          # Keep the runner alive until manually cancelled
          while true; do
            echo "[$(date)] VPS Active - Use Ctrl+C in workflow to terminate"
            sleep 300
          done
